modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/mrbysco/Coupons/issues"
license="MIT"

[[mods]]
modId="coupons"
version="${file.jarVersion}"
displayName="Coupons"
displayURL="https://minecraft.curseforge.com/projects/coupons"
authors="ShyNieke, Mrbysco"
description='''
You get discount and you get discount. EVERYBODY GETS DISCOUNT!
'''
[[dependencies.coupons]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"