modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/mrbysco/Coupons/issues"
license="MIT"

[[mods]]
modId="coupons"
version="${file.jarVersion}"
displayName="Coupons"
displayURL="https://minecraft.curseforge.com/projects/coupons"
authors="ShyNieke, Mrbysco"
description='''
You get discount and you get discount. EVERYBODY GETS DISCOUNT!
'''
[[dependencies.coupons]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.coupons]]
modId="forge"
mandatory=true
versionRange="[41.0.94,)"
ordering="NONE"
side="BOTH"