modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/mrbysco/Coupons/issues"
license="MIT"

[[mods]]
modId="coupons"
version="${file.jarVersion}"
displayName="Coupons"
displayURL="https://www.curseforge.com/minecraft/mc-mods/coupons"
authors="ShyNieke, Mrbysco"
description='''
You get discount and you get discount. EVERYBODY GETS DISCOUNT!
'''
[[dependencies.coupons]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.coupons]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"